### ISSUE TITLE
[Discord] Fix discord issue with webhooks

### ISSUE THREAD

**Issue by TheGoatGod** [GMC-Modding-Team/Community-Mod-Compilation-redux#150]
it worked on the old now deprecated repo when it wasn't part of the organization, the switch to redux made this fail. there were other things that broke going to the organization workflows and other needed stuff, eventually I want GitHub and discord to communicate properly.

**Todo**
- [ ] Find out how to fix the issue with discord 
  - [ ] Make all releases and tags post to #release
  - [ ] Make all announcements post to #annoucements
  - [ ] Make all issues post to issues #issues

**Optional**
- [ ] Create new channel for PRs
- [ ] Make all PRs post to
