### ISSUE TITLE
[Experimental] anti fungal equipment expansion 

### ISSUE THREAD

**Issue by TheGoatGod** [GMC-Modding-Team/Community-Mod-Compilation-redux#76]
### Description
the Anti fungal merge with additional content

### Part 1 [first instance]
- [x] merge anti fungal kit 
- [x] merge anti fungal locations
- [x] merge anti fungal gear 
- [x] change name to anti-fungal equipment
- [x] added content to make ammo work like material

### Part 2 [fixes]
- [x] fix for ammo thats exactly the same 
- [x] additional content
- [x] add pocket data to "antifungal gas sprayer" and additional fixes
- [x] fix up current content to modern standard

### Part 3 [additions and fixes]
- [x] "anti_fungicidal_sprayer" spawn able
 
### Pull requests
#69 has first instance of the mod merging
#77 this is the pr with the new stuff

**Comment by TheGoatGod** [comment]
letteral difference is `"drop": "fungus_bomb_act",`  and `"drop": "fungicidal_bomb_act",`
```
{
    "id": "40mm_fungus",
    "copy-from": "40x46mm_grenade",
    "type": "AMMO",
    "name": { "str": "40mm fungicidal gas grenade alternative" },
    "description": "A handmade 40mm grenade with a fungicide load.  It will burst in a cloud of toxic gas, deadly to fungus.",
    "drop": "fungus_bomb_act",
    "extend": { "effects": [ "NO_EMBED" ] }
  },
  {
    "id": "40mm_fungicidal",
    "copy-from": "40x46mm_grenade",
    "type": "AMMO",
    "name": { "str": "40mm fungicidal gas grenade", "str_pl": "40mm fungicidal gas grenades" },
    "description": "A 40 mm grenade bullet filled with fungicidal gas. For a while, we will keep releasing the sterilizing gas to the impact point.",
    "looks_like": "40x46mm_m433",
    "drop": "fungicidal_bomb_act",
    "extend": { "effects": [ "NO_EMBED" ] }
  }
```
